### ISSUE TITLE
Original Data

### ISSUE THREAD

**Issue by yh675** [nianticlabs/footprints#2]
Hi,

Thanks for releasing this cool work!

Is there anyway to get access to the original _handheld_ stereo dataset that you used to train your own model?

**Comment by mdfirman** [comment]
Hi – sorry, no, that data is owned by Niantic and we won't be releasing it.

We were careful to ensure that all our experiments and comparisons were done on public datasets (KITTI & Matterport) to ensure reproducibility. The handheld data was only used for some qualitative demonstrations.

However, with a stereo pair it should be fairly easy for you to capture equivalent data yourself.

Thanks
