### ISSUE TITLE
supplementary materials

### ISSUE THREAD

**Issue by pingping-lu** [nianticlabs/footprints#3]
It's really interesting work. I wonder where can we find the supplementary materials mentioned in your paper? Thanks~

**Comment by mdfirman** [comment]
Hi, thanks for your interest in this work.

I don't have a copy of the camera ready supplementary, but you can find a copy of the submission supplementary here:
http://michaelfirman.co.uk/files/Footprints_supplementary.pdf

The technical details are correct but the scores in the KITTI and Matterport tables don't correspond to those in the main paper, as we fixed up a couple of evaluation bugs between submission and camera ready.

Hope this helps! Thanks
